-- ============================================================
-- DATABASE ABSENSI TKJ - SUPABASE
-- Jalankan seluruh SQL ini di Supabase > SQL Editor
-- ============================================================

create table if not exists public.tkj_attendance (
    id bigint generated by default as identity primary key,
    name text not null,
    status text not null,
    time text not null,
    latitude double precision,
    longitude double precision,
    accuracy double precision,
    distance double precision,
    photo text,
    created_at timestamptz not null default now()
);

alter table public.tkj_attendance enable row level security;

-- Hapus policy lama jika ada
drop policy if exists "tkj_select" on public.tkj_attendance;
drop policy if exists "tkj_insert" on public.tkj_attendance;
drop policy if exists "tkj_delete" on public.tkj_attendance;

-- Semua pengunjung website boleh membaca data absensi.
create policy "tkj_select"
on public.tkj_attendance
for select
to anon
using (true);

-- Semua pengunjung website boleh menambahkan absensi.
create policy "tkj_insert"
on public.tkj_attendance
for insert
to anon
with check (true);

-- Tombol "Hapus Data" pada website menghapus semua data.
-- CATATAN: ini berarti siapa pun yang punya URL website dapat
-- menghapus data jika tombol tersebut ditekan.
create policy "tkj_delete"
on public.tkj_attendance
for delete
to anon
using (true);
